kind: ModelTraining
id: textclf-demo
spec:
  model:
    name: textclf
    version: 1.0
  toolchain: mlflow  # MLFlow training toolchain integration
  entrypoint: main
  workDir:   # MLproject location (in GitHub)
  hyperParameters:
    alpha: "1.0"
  resources:
    limits:
      cpu: 4024m
      memory: 4024Mi
    requests:
      cpu: 2024m
      memory: 2024Mi
  vcsName: odahu-flow-textclf